services:
  7d2d:
    build: .
    container_name: 7d2d_server
    restart: unless-stopped

    ports:
      - "26900:26900/tcp"
      - "26900:26900/udp"
      - "26901-26905:26901-26905/tcp"
      - "26901-26905:26901-26905/udp"
      - "8080:8080/tcp"

    volumes:
      - ./server/7d2d:/server/7d2d

  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yml
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml:ro
      - loki-data:/loki

  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - ./server/7d2d/logs:/logs:ro

  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/
    depends_on:
      - loki
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:v2.54.0
    container_name: prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    depends_on:
      - loki
      - promtail
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

volumes:
  grafana-data:
  loki-data:
  prometheus-data:
