services:
  7d2d:
    build: .
    container_name: 7d2d_server
    restart: unless-stopped

    ports:
      - "26900:26900/tcp"
      - "26900:26900/udp"
      - "26901-26905:26901-26905/tcp"
      - "26901-26905:26901-26905/udp"
      - "8080:8080/tcp"

    volumes:
      - ./server/7d2d:/server/7d2d
